sudo: required
dist: trusty

language: haxe

haxe:
  - "4.1.0"
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - yes | haxelib install all

script:
$scripts

deploy:
  - provider: script
    haxe: 4.1.0
    script: bash ./release_haxelib.sh $HAXELIB_PWD
    on:
      tags: true
