sudo: false
dist: trusty

language: haxe
node_js:
  - 12
  
haxe:
  - "3.4.7"
  - "4.1.0"
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - yes | haxelib install all

script:
  - haxe build.hxml
  - haxelib dev hxnew .
  - haxelib run hxnew -name MyProject1 -pack com.website
  - cd MyProject1/
  - haxe build.hxml
  - cd ../
  - haxelib run hxnew -name test.MyProject2 -target neko
  - cd test.MyProject2/
  - haxe build.hxml
  - haxe run.hxml
  - cd ../
  - haxelib run hxnew -name MyProject3 -target neko,nodejs -lib format
  - cd MyProject3/
  - haxe install.hxml
  - haxe build-neko.hxml
  - haxe run-neko.hxml
  - haxe build-nodejs.hxml
  - haxe run-nodejs.hxml
  - cd ../
  - haxelib run hxnew -name MyProject4 -pack com.website --lix
  - cd MyProject4/
  - npm run haxe build.hxml
  - cd ../
  - haxelib run hxnew -name test.MyProject5 -target neko --lix
  - cd test.MyProject5/
  - npm run haxe build.hxml
  - npm run haxe run.hxml
  - cd ../
  - haxelib run hxnew -name MyProject6 -target neko,nodejs -lib format --lix
  - cd MyProject6/
  - npm run haxe build-neko.hxml
  - npm run haxe run-neko.hxml
  - npm run haxe build-nodejs.hxml
  - npm run haxe run-nodejs.hxml
  - cd ../

notifications:
  email: false

deploy:
  - provider: script
    haxe: 4.1.0
    script: bash ./release_haxelib.sh $HAXELIB_PWD
    on:
      tags: true
