sudo: required
dist: trusty

language: haxe

haxe:
  - "3.4.0"
  - "3.4.4"
  - "development"

matrix:
  allow_failures:
    - haxe: development

install:
  - yes | haxelib install travix
  - haxelib run travix install

script:
  - haxe build.hxml
  - haxelib dev hxnew .
  - haxelib run hxnew -name MyProject1 -pack com.website
  - cd MyProject1/
  - haxe build.hxml
  - cd ../
  - haxelib run hxnew -name test.MyProject2 -target neko
  - cd test.MyProject2/
  - haxe build.hxml
  - haxe run.hxml
  - cd ../
  - haxelib run hxnew -name MyProject3 -target neko,nodejs -lib format
  - cd MyProject3/
  - haxe install.hxml
  - haxe build-neko.hxml
  - haxe run-neko.hxml
  - haxe build-nodejs.hxml
  - haxe run-nodejs.hxml

notifications:
  email: false

jobs:
  include:
    - stage: deploy
      os: linux
      script: skip
      after_success: haxelib run travix release
